# Generated by Django 5.0.1 on 2024-02-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_aiuser_age_aiuser_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'position',
                'verbose_name_plural': 'position',
            },
        ),
    ]
