# Generated by Django 5.0.1 on 2024-02-16 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.position')),
            ],
            options={
                'verbose_name': 'Candidates',
                'verbose_name_plural': 'Candidates',
            },
        ),
    ]
